### ISSUE TITLE
Windows WSL .env file permissions problem

### ISSUE THREAD

**Issue by Nargonath** [sholladay/envy#1]
`envy` requires you to put `600` as file permission on `.env`. Alas if your workspace is in the Windows land you cannot change the file permission from your bash environment. The problem is that Windows' permissions system is not as granular as Linux' is. You cannot set a `600` on it (at least I haven't found a way) however you can set `666`, `000` or `777`.

One way to solve this is changing the permissions requirements based on the platform running `envy`, we could settle for `666` when `process.platform === 'win32'`.

**Comment by Nargonath** [comment]
It might be a bit trickier than the possible solution mentioned above. I just ran `node -e "console.log(process.platform);"` in my bash terminal and I get back `linux`. I'm not sure we have a way of noticing we are running on WSL platform. Another solution I thought of could be to add an object parameter as a second argument with property `{ wsl: true }` so we could change our handling of the permission. The parameter would default to false and not be required so we wouldn't break other people install. What do you think?

**Comment by sholladay** [comment]
Thankfully, it is possible to detect WSL:
https://github.com/sindresorhus/is-wsl

The code [here](https://github.com/sholladay/envy/blob/a935c35ea1eb3240759a9a9fd343cf41b4ed2f32/index.js#L64) needs to assert that the file permissions are `666` when `isWsl || prcoess.platform === 'win32`, otherwise keep the existing behavior.

I'll want to set up [AppVeyor](https://www.appveyor.com/) and tests for this as well.

**Comment by Nargonath** [comment]
Alright! Sindre to the rescue! I looked up on Google but couldn't find information about how to detect it. Thanks for the help. I don't think I can make a PR before this weekend, if I have the time I will otherwise I'll do it this weekend.

**Comment by Nargonath** [comment]
By the way only the check on hidden `.env` file is problematic on Windows as you can pass the first test if you put `666` as your file permission. Do you still want to change it or shall I keep it as is?

**Comment by sholladay** [comment]
Ah yes, you are right. The `.env.example` check is already loose enough and we can leave it as-is. Updated my comment to reflect that.

**Comment by Nargonath** [comment]
I made a mistake when I explained the issue. On windows I can only make `777`, `555` or `000` permission. I guess this is fine if I require the file to `555` instead of `666`. Users would just have to modify the file as Administrator.
